package igstw.g7.modelo.pojos;

public class Plantilla {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plantilla.P_ID
     *
     * @mbggenerated Sat Nov 22 18:09:08 COT 2014
     */
    private Integer p_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plantilla.P_NOMBRE
     *
     * @mbggenerated Sat Nov 22 18:09:08 COT 2014
     */
    private String p_nombre;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plantilla.P_CONSULTA_SELECT
     *
     * @mbggenerated Sat Nov 22 18:09:08 COT 2014
     */
    private String p_consulta_select;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plantilla.P_CONSULTA_ORDER
     *
     * @mbggenerated Sat Nov 22 18:09:08 COT 2014
     */
    private String p_consulta_order;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plantilla.P_N_HEADER
     *
     * @mbggenerated Sat Nov 22 18:09:08 COT 2014
     */
    private Integer p_n_header;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plantilla.P_N_FOOTER
     *
     * @mbggenerated Sat Nov 22 18:09:08 COT 2014
     */
    private Integer p_n_footer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plantilla.P_N_DETAIL
     *
     * @mbggenerated Sat Nov 22 18:09:08 COT 2014
     */
    private Integer p_n_detail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plantilla.P_ESTADO
     *
     * @mbggenerated Sat Nov 22 18:09:08 COT 2014
     */
    private String p_estado;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plantilla.P_ID
     *
     * @return the value of plantilla.P_ID
     *
     * @mbggenerated Sat Nov 22 18:09:08 COT 2014
     */
    public Integer getP_id() {
        return p_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plantilla.P_ID
     *
     * @param p_id the value for plantilla.P_ID
     *
     * @mbggenerated Sat Nov 22 18:09:08 COT 2014
     */
    public void setP_id(Integer p_id) {
        this.p_id = p_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plantilla.P_NOMBRE
     *
     * @return the value of plantilla.P_NOMBRE
     *
     * @mbggenerated Sat Nov 22 18:09:08 COT 2014
     */
    public String getP_nombre() {
        return p_nombre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plantilla.P_NOMBRE
     *
     * @param p_nombre the value for plantilla.P_NOMBRE
     *
     * @mbggenerated Sat Nov 22 18:09:08 COT 2014
     */
    public void setP_nombre(String p_nombre) {
        this.p_nombre = p_nombre == null ? null : p_nombre.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plantilla.P_CONSULTA_SELECT
     *
     * @return the value of plantilla.P_CONSULTA_SELECT
     *
     * @mbggenerated Sat Nov 22 18:09:08 COT 2014
     */
    public String getP_consulta_select() {
        return p_consulta_select;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plantilla.P_CONSULTA_SELECT
     *
     * @param p_consulta_select the value for plantilla.P_CONSULTA_SELECT
     *
     * @mbggenerated Sat Nov 22 18:09:08 COT 2014
     */
    public void setP_consulta_select(String p_consulta_select) {
        this.p_consulta_select = p_consulta_select == null ? null : p_consulta_select.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plantilla.P_CONSULTA_ORDER
     *
     * @return the value of plantilla.P_CONSULTA_ORDER
     *
     * @mbggenerated Sat Nov 22 18:09:08 COT 2014
     */
    public String getP_consulta_order() {
        return p_consulta_order;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plantilla.P_CONSULTA_ORDER
     *
     * @param p_consulta_order the value for plantilla.P_CONSULTA_ORDER
     *
     * @mbggenerated Sat Nov 22 18:09:08 COT 2014
     */
    public void setP_consulta_order(String p_consulta_order) {
        this.p_consulta_order = p_consulta_order == null ? null : p_consulta_order.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plantilla.P_N_HEADER
     *
     * @return the value of plantilla.P_N_HEADER
     *
     * @mbggenerated Sat Nov 22 18:09:08 COT 2014
     */
    public Integer getP_n_header() {
        return p_n_header;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plantilla.P_N_HEADER
     *
     * @param p_n_header the value for plantilla.P_N_HEADER
     *
     * @mbggenerated Sat Nov 22 18:09:08 COT 2014
     */
    public void setP_n_header(Integer p_n_header) {
        this.p_n_header = p_n_header;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plantilla.P_N_FOOTER
     *
     * @return the value of plantilla.P_N_FOOTER
     *
     * @mbggenerated Sat Nov 22 18:09:08 COT 2014
     */
    public Integer getP_n_footer() {
        return p_n_footer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plantilla.P_N_FOOTER
     *
     * @param p_n_footer the value for plantilla.P_N_FOOTER
     *
     * @mbggenerated Sat Nov 22 18:09:08 COT 2014
     */
    public void setP_n_footer(Integer p_n_footer) {
        this.p_n_footer = p_n_footer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plantilla.P_N_DETAIL
     *
     * @return the value of plantilla.P_N_DETAIL
     *
     * @mbggenerated Sat Nov 22 18:09:08 COT 2014
     */
    public Integer getP_n_detail() {
        return p_n_detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plantilla.P_N_DETAIL
     *
     * @param p_n_detail the value for plantilla.P_N_DETAIL
     *
     * @mbggenerated Sat Nov 22 18:09:08 COT 2014
     */
    public void setP_n_detail(Integer p_n_detail) {
        this.p_n_detail = p_n_detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plantilla.P_ESTADO
     *
     * @return the value of plantilla.P_ESTADO
     *
     * @mbggenerated Sat Nov 22 18:09:08 COT 2014
     */
    public String getP_estado() {
        return p_estado;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plantilla.P_ESTADO
     *
     * @param p_estado the value for plantilla.P_ESTADO
     *
     * @mbggenerated Sat Nov 22 18:09:08 COT 2014
     */
    public void setP_estado(String p_estado) {
        this.p_estado = p_estado == null ? null : p_estado.trim();
    }
}