package igstw.g7.modelo.pojos;

import java.util.ArrayList;
import java.util.List;

public class PlantillaExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table plantilla
     *
     * @mbggenerated Sat Nov 22 18:09:08 COT 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table plantilla
     *
     * @mbggenerated Sat Nov 22 18:09:08 COT 2014
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table plantilla
     *
     * @mbggenerated Sat Nov 22 18:09:08 COT 2014
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plantilla
     *
     * @mbggenerated Sat Nov 22 18:09:08 COT 2014
     */
    public PlantillaExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plantilla
     *
     * @mbggenerated Sat Nov 22 18:09:08 COT 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plantilla
     *
     * @mbggenerated Sat Nov 22 18:09:08 COT 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plantilla
     *
     * @mbggenerated Sat Nov 22 18:09:08 COT 2014
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plantilla
     *
     * @mbggenerated Sat Nov 22 18:09:08 COT 2014
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plantilla
     *
     * @mbggenerated Sat Nov 22 18:09:08 COT 2014
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plantilla
     *
     * @mbggenerated Sat Nov 22 18:09:08 COT 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plantilla
     *
     * @mbggenerated Sat Nov 22 18:09:08 COT 2014
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plantilla
     *
     * @mbggenerated Sat Nov 22 18:09:08 COT 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plantilla
     *
     * @mbggenerated Sat Nov 22 18:09:08 COT 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plantilla
     *
     * @mbggenerated Sat Nov 22 18:09:08 COT 2014
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table plantilla
     *
     * @mbggenerated Sat Nov 22 18:09:08 COT 2014
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andP_idIsNull() {
            addCriterion("P_ID is null");
            return (Criteria) this;
        }

        public Criteria andP_idIsNotNull() {
            addCriterion("P_ID is not null");
            return (Criteria) this;
        }

        public Criteria andP_idEqualTo(Integer value) {
            addCriterion("P_ID =", value, "p_id");
            return (Criteria) this;
        }

        public Criteria andP_idNotEqualTo(Integer value) {
            addCriterion("P_ID <>", value, "p_id");
            return (Criteria) this;
        }

        public Criteria andP_idGreaterThan(Integer value) {
            addCriterion("P_ID >", value, "p_id");
            return (Criteria) this;
        }

        public Criteria andP_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("P_ID >=", value, "p_id");
            return (Criteria) this;
        }

        public Criteria andP_idLessThan(Integer value) {
            addCriterion("P_ID <", value, "p_id");
            return (Criteria) this;
        }

        public Criteria andP_idLessThanOrEqualTo(Integer value) {
            addCriterion("P_ID <=", value, "p_id");
            return (Criteria) this;
        }

        public Criteria andP_idIn(List<Integer> values) {
            addCriterion("P_ID in", values, "p_id");
            return (Criteria) this;
        }

        public Criteria andP_idNotIn(List<Integer> values) {
            addCriterion("P_ID not in", values, "p_id");
            return (Criteria) this;
        }

        public Criteria andP_idBetween(Integer value1, Integer value2) {
            addCriterion("P_ID between", value1, value2, "p_id");
            return (Criteria) this;
        }

        public Criteria andP_idNotBetween(Integer value1, Integer value2) {
            addCriterion("P_ID not between", value1, value2, "p_id");
            return (Criteria) this;
        }

        public Criteria andP_nombreIsNull() {
            addCriterion("P_NOMBRE is null");
            return (Criteria) this;
        }

        public Criteria andP_nombreIsNotNull() {
            addCriterion("P_NOMBRE is not null");
            return (Criteria) this;
        }

        public Criteria andP_nombreEqualTo(String value) {
            addCriterion("P_NOMBRE =", value, "p_nombre");
            return (Criteria) this;
        }

        public Criteria andP_nombreNotEqualTo(String value) {
            addCriterion("P_NOMBRE <>", value, "p_nombre");
            return (Criteria) this;
        }

        public Criteria andP_nombreGreaterThan(String value) {
            addCriterion("P_NOMBRE >", value, "p_nombre");
            return (Criteria) this;
        }

        public Criteria andP_nombreGreaterThanOrEqualTo(String value) {
            addCriterion("P_NOMBRE >=", value, "p_nombre");
            return (Criteria) this;
        }

        public Criteria andP_nombreLessThan(String value) {
            addCriterion("P_NOMBRE <", value, "p_nombre");
            return (Criteria) this;
        }

        public Criteria andP_nombreLessThanOrEqualTo(String value) {
            addCriterion("P_NOMBRE <=", value, "p_nombre");
            return (Criteria) this;
        }

        public Criteria andP_nombreLike(String value) {
            addCriterion("P_NOMBRE like", value, "p_nombre");
            return (Criteria) this;
        }

        public Criteria andP_nombreNotLike(String value) {
            addCriterion("P_NOMBRE not like", value, "p_nombre");
            return (Criteria) this;
        }

        public Criteria andP_nombreIn(List<String> values) {
            addCriterion("P_NOMBRE in", values, "p_nombre");
            return (Criteria) this;
        }

        public Criteria andP_nombreNotIn(List<String> values) {
            addCriterion("P_NOMBRE not in", values, "p_nombre");
            return (Criteria) this;
        }

        public Criteria andP_nombreBetween(String value1, String value2) {
            addCriterion("P_NOMBRE between", value1, value2, "p_nombre");
            return (Criteria) this;
        }

        public Criteria andP_nombreNotBetween(String value1, String value2) {
            addCriterion("P_NOMBRE not between", value1, value2, "p_nombre");
            return (Criteria) this;
        }

        public Criteria andP_consulta_selectIsNull() {
            addCriterion("P_CONSULTA_SELECT is null");
            return (Criteria) this;
        }

        public Criteria andP_consulta_selectIsNotNull() {
            addCriterion("P_CONSULTA_SELECT is not null");
            return (Criteria) this;
        }

        public Criteria andP_consulta_selectEqualTo(String value) {
            addCriterion("P_CONSULTA_SELECT =", value, "p_consulta_select");
            return (Criteria) this;
        }

        public Criteria andP_consulta_selectNotEqualTo(String value) {
            addCriterion("P_CONSULTA_SELECT <>", value, "p_consulta_select");
            return (Criteria) this;
        }

        public Criteria andP_consulta_selectGreaterThan(String value) {
            addCriterion("P_CONSULTA_SELECT >", value, "p_consulta_select");
            return (Criteria) this;
        }

        public Criteria andP_consulta_selectGreaterThanOrEqualTo(String value) {
            addCriterion("P_CONSULTA_SELECT >=", value, "p_consulta_select");
            return (Criteria) this;
        }

        public Criteria andP_consulta_selectLessThan(String value) {
            addCriterion("P_CONSULTA_SELECT <", value, "p_consulta_select");
            return (Criteria) this;
        }

        public Criteria andP_consulta_selectLessThanOrEqualTo(String value) {
            addCriterion("P_CONSULTA_SELECT <=", value, "p_consulta_select");
            return (Criteria) this;
        }

        public Criteria andP_consulta_selectLike(String value) {
            addCriterion("P_CONSULTA_SELECT like", value, "p_consulta_select");
            return (Criteria) this;
        }

        public Criteria andP_consulta_selectNotLike(String value) {
            addCriterion("P_CONSULTA_SELECT not like", value, "p_consulta_select");
            return (Criteria) this;
        }

        public Criteria andP_consulta_selectIn(List<String> values) {
            addCriterion("P_CONSULTA_SELECT in", values, "p_consulta_select");
            return (Criteria) this;
        }

        public Criteria andP_consulta_selectNotIn(List<String> values) {
            addCriterion("P_CONSULTA_SELECT not in", values, "p_consulta_select");
            return (Criteria) this;
        }

        public Criteria andP_consulta_selectBetween(String value1, String value2) {
            addCriterion("P_CONSULTA_SELECT between", value1, value2, "p_consulta_select");
            return (Criteria) this;
        }

        public Criteria andP_consulta_selectNotBetween(String value1, String value2) {
            addCriterion("P_CONSULTA_SELECT not between", value1, value2, "p_consulta_select");
            return (Criteria) this;
        }

        public Criteria andP_consulta_orderIsNull() {
            addCriterion("P_CONSULTA_ORDER is null");
            return (Criteria) this;
        }

        public Criteria andP_consulta_orderIsNotNull() {
            addCriterion("P_CONSULTA_ORDER is not null");
            return (Criteria) this;
        }

        public Criteria andP_consulta_orderEqualTo(String value) {
            addCriterion("P_CONSULTA_ORDER =", value, "p_consulta_order");
            return (Criteria) this;
        }

        public Criteria andP_consulta_orderNotEqualTo(String value) {
            addCriterion("P_CONSULTA_ORDER <>", value, "p_consulta_order");
            return (Criteria) this;
        }

        public Criteria andP_consulta_orderGreaterThan(String value) {
            addCriterion("P_CONSULTA_ORDER >", value, "p_consulta_order");
            return (Criteria) this;
        }

        public Criteria andP_consulta_orderGreaterThanOrEqualTo(String value) {
            addCriterion("P_CONSULTA_ORDER >=", value, "p_consulta_order");
            return (Criteria) this;
        }

        public Criteria andP_consulta_orderLessThan(String value) {
            addCriterion("P_CONSULTA_ORDER <", value, "p_consulta_order");
            return (Criteria) this;
        }

        public Criteria andP_consulta_orderLessThanOrEqualTo(String value) {
            addCriterion("P_CONSULTA_ORDER <=", value, "p_consulta_order");
            return (Criteria) this;
        }

        public Criteria andP_consulta_orderLike(String value) {
            addCriterion("P_CONSULTA_ORDER like", value, "p_consulta_order");
            return (Criteria) this;
        }

        public Criteria andP_consulta_orderNotLike(String value) {
            addCriterion("P_CONSULTA_ORDER not like", value, "p_consulta_order");
            return (Criteria) this;
        }

        public Criteria andP_consulta_orderIn(List<String> values) {
            addCriterion("P_CONSULTA_ORDER in", values, "p_consulta_order");
            return (Criteria) this;
        }

        public Criteria andP_consulta_orderNotIn(List<String> values) {
            addCriterion("P_CONSULTA_ORDER not in", values, "p_consulta_order");
            return (Criteria) this;
        }

        public Criteria andP_consulta_orderBetween(String value1, String value2) {
            addCriterion("P_CONSULTA_ORDER between", value1, value2, "p_consulta_order");
            return (Criteria) this;
        }

        public Criteria andP_consulta_orderNotBetween(String value1, String value2) {
            addCriterion("P_CONSULTA_ORDER not between", value1, value2, "p_consulta_order");
            return (Criteria) this;
        }

        public Criteria andP_n_headerIsNull() {
            addCriterion("P_N_HEADER is null");
            return (Criteria) this;
        }

        public Criteria andP_n_headerIsNotNull() {
            addCriterion("P_N_HEADER is not null");
            return (Criteria) this;
        }

        public Criteria andP_n_headerEqualTo(Integer value) {
            addCriterion("P_N_HEADER =", value, "p_n_header");
            return (Criteria) this;
        }

        public Criteria andP_n_headerNotEqualTo(Integer value) {
            addCriterion("P_N_HEADER <>", value, "p_n_header");
            return (Criteria) this;
        }

        public Criteria andP_n_headerGreaterThan(Integer value) {
            addCriterion("P_N_HEADER >", value, "p_n_header");
            return (Criteria) this;
        }

        public Criteria andP_n_headerGreaterThanOrEqualTo(Integer value) {
            addCriterion("P_N_HEADER >=", value, "p_n_header");
            return (Criteria) this;
        }

        public Criteria andP_n_headerLessThan(Integer value) {
            addCriterion("P_N_HEADER <", value, "p_n_header");
            return (Criteria) this;
        }

        public Criteria andP_n_headerLessThanOrEqualTo(Integer value) {
            addCriterion("P_N_HEADER <=", value, "p_n_header");
            return (Criteria) this;
        }

        public Criteria andP_n_headerIn(List<Integer> values) {
            addCriterion("P_N_HEADER in", values, "p_n_header");
            return (Criteria) this;
        }

        public Criteria andP_n_headerNotIn(List<Integer> values) {
            addCriterion("P_N_HEADER not in", values, "p_n_header");
            return (Criteria) this;
        }

        public Criteria andP_n_headerBetween(Integer value1, Integer value2) {
            addCriterion("P_N_HEADER between", value1, value2, "p_n_header");
            return (Criteria) this;
        }

        public Criteria andP_n_headerNotBetween(Integer value1, Integer value2) {
            addCriterion("P_N_HEADER not between", value1, value2, "p_n_header");
            return (Criteria) this;
        }

        public Criteria andP_n_footerIsNull() {
            addCriterion("P_N_FOOTER is null");
            return (Criteria) this;
        }

        public Criteria andP_n_footerIsNotNull() {
            addCriterion("P_N_FOOTER is not null");
            return (Criteria) this;
        }

        public Criteria andP_n_footerEqualTo(Integer value) {
            addCriterion("P_N_FOOTER =", value, "p_n_footer");
            return (Criteria) this;
        }

        public Criteria andP_n_footerNotEqualTo(Integer value) {
            addCriterion("P_N_FOOTER <>", value, "p_n_footer");
            return (Criteria) this;
        }

        public Criteria andP_n_footerGreaterThan(Integer value) {
            addCriterion("P_N_FOOTER >", value, "p_n_footer");
            return (Criteria) this;
        }

        public Criteria andP_n_footerGreaterThanOrEqualTo(Integer value) {
            addCriterion("P_N_FOOTER >=", value, "p_n_footer");
            return (Criteria) this;
        }

        public Criteria andP_n_footerLessThan(Integer value) {
            addCriterion("P_N_FOOTER <", value, "p_n_footer");
            return (Criteria) this;
        }

        public Criteria andP_n_footerLessThanOrEqualTo(Integer value) {
            addCriterion("P_N_FOOTER <=", value, "p_n_footer");
            return (Criteria) this;
        }

        public Criteria andP_n_footerIn(List<Integer> values) {
            addCriterion("P_N_FOOTER in", values, "p_n_footer");
            return (Criteria) this;
        }

        public Criteria andP_n_footerNotIn(List<Integer> values) {
            addCriterion("P_N_FOOTER not in", values, "p_n_footer");
            return (Criteria) this;
        }

        public Criteria andP_n_footerBetween(Integer value1, Integer value2) {
            addCriterion("P_N_FOOTER between", value1, value2, "p_n_footer");
            return (Criteria) this;
        }

        public Criteria andP_n_footerNotBetween(Integer value1, Integer value2) {
            addCriterion("P_N_FOOTER not between", value1, value2, "p_n_footer");
            return (Criteria) this;
        }

        public Criteria andP_n_detailIsNull() {
            addCriterion("P_N_DETAIL is null");
            return (Criteria) this;
        }

        public Criteria andP_n_detailIsNotNull() {
            addCriterion("P_N_DETAIL is not null");
            return (Criteria) this;
        }

        public Criteria andP_n_detailEqualTo(Integer value) {
            addCriterion("P_N_DETAIL =", value, "p_n_detail");
            return (Criteria) this;
        }

        public Criteria andP_n_detailNotEqualTo(Integer value) {
            addCriterion("P_N_DETAIL <>", value, "p_n_detail");
            return (Criteria) this;
        }

        public Criteria andP_n_detailGreaterThan(Integer value) {
            addCriterion("P_N_DETAIL >", value, "p_n_detail");
            return (Criteria) this;
        }

        public Criteria andP_n_detailGreaterThanOrEqualTo(Integer value) {
            addCriterion("P_N_DETAIL >=", value, "p_n_detail");
            return (Criteria) this;
        }

        public Criteria andP_n_detailLessThan(Integer value) {
            addCriterion("P_N_DETAIL <", value, "p_n_detail");
            return (Criteria) this;
        }

        public Criteria andP_n_detailLessThanOrEqualTo(Integer value) {
            addCriterion("P_N_DETAIL <=", value, "p_n_detail");
            return (Criteria) this;
        }

        public Criteria andP_n_detailIn(List<Integer> values) {
            addCriterion("P_N_DETAIL in", values, "p_n_detail");
            return (Criteria) this;
        }

        public Criteria andP_n_detailNotIn(List<Integer> values) {
            addCriterion("P_N_DETAIL not in", values, "p_n_detail");
            return (Criteria) this;
        }

        public Criteria andP_n_detailBetween(Integer value1, Integer value2) {
            addCriterion("P_N_DETAIL between", value1, value2, "p_n_detail");
            return (Criteria) this;
        }

        public Criteria andP_n_detailNotBetween(Integer value1, Integer value2) {
            addCriterion("P_N_DETAIL not between", value1, value2, "p_n_detail");
            return (Criteria) this;
        }

        public Criteria andP_estadoIsNull() {
            addCriterion("P_ESTADO is null");
            return (Criteria) this;
        }

        public Criteria andP_estadoIsNotNull() {
            addCriterion("P_ESTADO is not null");
            return (Criteria) this;
        }

        public Criteria andP_estadoEqualTo(String value) {
            addCriterion("P_ESTADO =", value, "p_estado");
            return (Criteria) this;
        }

        public Criteria andP_estadoNotEqualTo(String value) {
            addCriterion("P_ESTADO <>", value, "p_estado");
            return (Criteria) this;
        }

        public Criteria andP_estadoGreaterThan(String value) {
            addCriterion("P_ESTADO >", value, "p_estado");
            return (Criteria) this;
        }

        public Criteria andP_estadoGreaterThanOrEqualTo(String value) {
            addCriterion("P_ESTADO >=", value, "p_estado");
            return (Criteria) this;
        }

        public Criteria andP_estadoLessThan(String value) {
            addCriterion("P_ESTADO <", value, "p_estado");
            return (Criteria) this;
        }

        public Criteria andP_estadoLessThanOrEqualTo(String value) {
            addCriterion("P_ESTADO <=", value, "p_estado");
            return (Criteria) this;
        }

        public Criteria andP_estadoLike(String value) {
            addCriterion("P_ESTADO like", value, "p_estado");
            return (Criteria) this;
        }

        public Criteria andP_estadoNotLike(String value) {
            addCriterion("P_ESTADO not like", value, "p_estado");
            return (Criteria) this;
        }

        public Criteria andP_estadoIn(List<String> values) {
            addCriterion("P_ESTADO in", values, "p_estado");
            return (Criteria) this;
        }

        public Criteria andP_estadoNotIn(List<String> values) {
            addCriterion("P_ESTADO not in", values, "p_estado");
            return (Criteria) this;
        }

        public Criteria andP_estadoBetween(String value1, String value2) {
            addCriterion("P_ESTADO between", value1, value2, "p_estado");
            return (Criteria) this;
        }

        public Criteria andP_estadoNotBetween(String value1, String value2) {
            addCriterion("P_ESTADO not between", value1, value2, "p_estado");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table plantilla
     *
     * @mbggenerated do_not_delete_during_merge Sat Nov 22 18:09:08 COT 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table plantilla
     *
     * @mbggenerated Sat Nov 22 18:09:08 COT 2014
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}