package igstw.g7.modelo.pojos;

import java.io.Serializable;

public class Usuario implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usuario.U_COD
     *
     * @mbggenerated Sat Nov 22 18:09:08 COT 2014
     */
    private String u_cod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usuario.U_NOM
     *
     * @mbggenerated Sat Nov 22 18:09:08 COT 2014
     */
    private String u_nom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usuario.U_APE_PAT
     *
     * @mbggenerated Sat Nov 22 18:09:08 COT 2014
     */
    private String u_ape_pat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usuario.U_APE_MAT
     *
     * @mbggenerated Sat Nov 22 18:09:08 COT 2014
     */
    private String u_ape_mat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usuario.U_CON
     *
     * @mbggenerated Sat Nov 22 18:09:08 COT 2014
     */
    private String u_con;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usuario.U_ESTADO
     *
     * @mbggenerated Sat Nov 22 18:09:08 COT 2014
     */
    private String u_estado;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usuario.ROL_ID
     *
     * @mbggenerated Sat Nov 22 18:09:08 COT 2014
     */
    private Integer rol_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usuario.U_COD
     *
     * @return the value of usuario.U_COD
     *
     * @mbggenerated Sat Nov 22 18:09:08 COT 2014
     */
    public String getU_cod() {
        return u_cod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usuario.U_COD
     *
     * @param u_cod the value for usuario.U_COD
     *
     * @mbggenerated Sat Nov 22 18:09:08 COT 2014
     */
    public void setU_cod(String u_cod) {
        this.u_cod = u_cod == null ? null : u_cod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usuario.U_NOM
     *
     * @return the value of usuario.U_NOM
     *
     * @mbggenerated Sat Nov 22 18:09:08 COT 2014
     */
    public String getU_nom() {
        return u_nom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usuario.U_NOM
     *
     * @param u_nom the value for usuario.U_NOM
     *
     * @mbggenerated Sat Nov 22 18:09:08 COT 2014
     */
    public void setU_nom(String u_nom) {
        this.u_nom = u_nom == null ? null : u_nom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usuario.U_APE_PAT
     *
     * @return the value of usuario.U_APE_PAT
     *
     * @mbggenerated Sat Nov 22 18:09:08 COT 2014
     */
    public String getU_ape_pat() {
        return u_ape_pat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usuario.U_APE_PAT
     *
     * @param u_ape_pat the value for usuario.U_APE_PAT
     *
     * @mbggenerated Sat Nov 22 18:09:08 COT 2014
     */
    public void setU_ape_pat(String u_ape_pat) {
        this.u_ape_pat = u_ape_pat == null ? null : u_ape_pat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usuario.U_APE_MAT
     *
     * @return the value of usuario.U_APE_MAT
     *
     * @mbggenerated Sat Nov 22 18:09:08 COT 2014
     */
    public String getU_ape_mat() {
        return u_ape_mat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usuario.U_APE_MAT
     *
     * @param u_ape_mat the value for usuario.U_APE_MAT
     *
     * @mbggenerated Sat Nov 22 18:09:08 COT 2014
     */
    public void setU_ape_mat(String u_ape_mat) {
        this.u_ape_mat = u_ape_mat == null ? null : u_ape_mat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usuario.U_CON
     *
     * @return the value of usuario.U_CON
     *
     * @mbggenerated Sat Nov 22 18:09:08 COT 2014
     */
    public String getU_con() {
        return u_con;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usuario.U_CON
     *
     * @param u_con the value for usuario.U_CON
     *
     * @mbggenerated Sat Nov 22 18:09:08 COT 2014
     */
    public void setU_con(String u_con) {
        this.u_con = u_con == null ? null : u_con.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usuario.U_ESTADO
     *
     * @return the value of usuario.U_ESTADO
     *
     * @mbggenerated Sat Nov 22 18:09:08 COT 2014
     */
    public String getU_estado() {
        return u_estado;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usuario.U_ESTADO
     *
     * @param u_estado the value for usuario.U_ESTADO
     *
     * @mbggenerated Sat Nov 22 18:09:08 COT 2014
     */
    public void setU_estado(String u_estado) {
        this.u_estado = u_estado == null ? null : u_estado.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usuario.ROL_ID
     *
     * @return the value of usuario.ROL_ID
     *
     * @mbggenerated Sat Nov 22 18:09:08 COT 2014
     */
    public Integer getRol_id() {
        return rol_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usuario.ROL_ID
     *
     * @param rol_id the value for usuario.ROL_ID
     *
     * @mbggenerated Sat Nov 22 18:09:08 COT 2014
     */
    public void setRol_id(Integer rol_id) {
        this.rol_id = rol_id;
    }
}