package igstw.g7.modelo.pojos;

import java.util.ArrayList;
import java.util.List;

public class UsuarioExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table usuario
     *
     * @mbggenerated Sat Nov 22 18:09:08 COT 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table usuario
     *
     * @mbggenerated Sat Nov 22 18:09:08 COT 2014
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table usuario
     *
     * @mbggenerated Sat Nov 22 18:09:08 COT 2014
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usuario
     *
     * @mbggenerated Sat Nov 22 18:09:08 COT 2014
     */
    public UsuarioExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usuario
     *
     * @mbggenerated Sat Nov 22 18:09:08 COT 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usuario
     *
     * @mbggenerated Sat Nov 22 18:09:08 COT 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usuario
     *
     * @mbggenerated Sat Nov 22 18:09:08 COT 2014
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usuario
     *
     * @mbggenerated Sat Nov 22 18:09:08 COT 2014
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usuario
     *
     * @mbggenerated Sat Nov 22 18:09:08 COT 2014
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usuario
     *
     * @mbggenerated Sat Nov 22 18:09:08 COT 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usuario
     *
     * @mbggenerated Sat Nov 22 18:09:08 COT 2014
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usuario
     *
     * @mbggenerated Sat Nov 22 18:09:08 COT 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usuario
     *
     * @mbggenerated Sat Nov 22 18:09:08 COT 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usuario
     *
     * @mbggenerated Sat Nov 22 18:09:08 COT 2014
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table usuario
     *
     * @mbggenerated Sat Nov 22 18:09:08 COT 2014
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andU_codIsNull() {
            addCriterion("U_COD is null");
            return (Criteria) this;
        }

        public Criteria andU_codIsNotNull() {
            addCriterion("U_COD is not null");
            return (Criteria) this;
        }

        public Criteria andU_codEqualTo(String value) {
            addCriterion("U_COD =", value, "u_cod");
            return (Criteria) this;
        }

        public Criteria andU_codNotEqualTo(String value) {
            addCriterion("U_COD <>", value, "u_cod");
            return (Criteria) this;
        }

        public Criteria andU_codGreaterThan(String value) {
            addCriterion("U_COD >", value, "u_cod");
            return (Criteria) this;
        }

        public Criteria andU_codGreaterThanOrEqualTo(String value) {
            addCriterion("U_COD >=", value, "u_cod");
            return (Criteria) this;
        }

        public Criteria andU_codLessThan(String value) {
            addCriterion("U_COD <", value, "u_cod");
            return (Criteria) this;
        }

        public Criteria andU_codLessThanOrEqualTo(String value) {
            addCriterion("U_COD <=", value, "u_cod");
            return (Criteria) this;
        }

        public Criteria andU_codLike(String value) {
            addCriterion("U_COD like", value, "u_cod");
            return (Criteria) this;
        }

        public Criteria andU_codNotLike(String value) {
            addCriterion("U_COD not like", value, "u_cod");
            return (Criteria) this;
        }

        public Criteria andU_codIn(List<String> values) {
            addCriterion("U_COD in", values, "u_cod");
            return (Criteria) this;
        }

        public Criteria andU_codNotIn(List<String> values) {
            addCriterion("U_COD not in", values, "u_cod");
            return (Criteria) this;
        }

        public Criteria andU_codBetween(String value1, String value2) {
            addCriterion("U_COD between", value1, value2, "u_cod");
            return (Criteria) this;
        }

        public Criteria andU_codNotBetween(String value1, String value2) {
            addCriterion("U_COD not between", value1, value2, "u_cod");
            return (Criteria) this;
        }

        public Criteria andU_nomIsNull() {
            addCriterion("U_NOM is null");
            return (Criteria) this;
        }

        public Criteria andU_nomIsNotNull() {
            addCriterion("U_NOM is not null");
            return (Criteria) this;
        }

        public Criteria andU_nomEqualTo(String value) {
            addCriterion("U_NOM =", value, "u_nom");
            return (Criteria) this;
        }

        public Criteria andU_nomNotEqualTo(String value) {
            addCriterion("U_NOM <>", value, "u_nom");
            return (Criteria) this;
        }

        public Criteria andU_nomGreaterThan(String value) {
            addCriterion("U_NOM >", value, "u_nom");
            return (Criteria) this;
        }

        public Criteria andU_nomGreaterThanOrEqualTo(String value) {
            addCriterion("U_NOM >=", value, "u_nom");
            return (Criteria) this;
        }

        public Criteria andU_nomLessThan(String value) {
            addCriterion("U_NOM <", value, "u_nom");
            return (Criteria) this;
        }

        public Criteria andU_nomLessThanOrEqualTo(String value) {
            addCriterion("U_NOM <=", value, "u_nom");
            return (Criteria) this;
        }

        public Criteria andU_nomLike(String value) {
            addCriterion("U_NOM like", value, "u_nom");
            return (Criteria) this;
        }

        public Criteria andU_nomNotLike(String value) {
            addCriterion("U_NOM not like", value, "u_nom");
            return (Criteria) this;
        }

        public Criteria andU_nomIn(List<String> values) {
            addCriterion("U_NOM in", values, "u_nom");
            return (Criteria) this;
        }

        public Criteria andU_nomNotIn(List<String> values) {
            addCriterion("U_NOM not in", values, "u_nom");
            return (Criteria) this;
        }

        public Criteria andU_nomBetween(String value1, String value2) {
            addCriterion("U_NOM between", value1, value2, "u_nom");
            return (Criteria) this;
        }

        public Criteria andU_nomNotBetween(String value1, String value2) {
            addCriterion("U_NOM not between", value1, value2, "u_nom");
            return (Criteria) this;
        }

        public Criteria andU_ape_patIsNull() {
            addCriterion("U_APE_PAT is null");
            return (Criteria) this;
        }

        public Criteria andU_ape_patIsNotNull() {
            addCriterion("U_APE_PAT is not null");
            return (Criteria) this;
        }

        public Criteria andU_ape_patEqualTo(String value) {
            addCriterion("U_APE_PAT =", value, "u_ape_pat");
            return (Criteria) this;
        }

        public Criteria andU_ape_patNotEqualTo(String value) {
            addCriterion("U_APE_PAT <>", value, "u_ape_pat");
            return (Criteria) this;
        }

        public Criteria andU_ape_patGreaterThan(String value) {
            addCriterion("U_APE_PAT >", value, "u_ape_pat");
            return (Criteria) this;
        }

        public Criteria andU_ape_patGreaterThanOrEqualTo(String value) {
            addCriterion("U_APE_PAT >=", value, "u_ape_pat");
            return (Criteria) this;
        }

        public Criteria andU_ape_patLessThan(String value) {
            addCriterion("U_APE_PAT <", value, "u_ape_pat");
            return (Criteria) this;
        }

        public Criteria andU_ape_patLessThanOrEqualTo(String value) {
            addCriterion("U_APE_PAT <=", value, "u_ape_pat");
            return (Criteria) this;
        }

        public Criteria andU_ape_patLike(String value) {
            addCriterion("U_APE_PAT like", value, "u_ape_pat");
            return (Criteria) this;
        }

        public Criteria andU_ape_patNotLike(String value) {
            addCriterion("U_APE_PAT not like", value, "u_ape_pat");
            return (Criteria) this;
        }

        public Criteria andU_ape_patIn(List<String> values) {
            addCriterion("U_APE_PAT in", values, "u_ape_pat");
            return (Criteria) this;
        }

        public Criteria andU_ape_patNotIn(List<String> values) {
            addCriterion("U_APE_PAT not in", values, "u_ape_pat");
            return (Criteria) this;
        }

        public Criteria andU_ape_patBetween(String value1, String value2) {
            addCriterion("U_APE_PAT between", value1, value2, "u_ape_pat");
            return (Criteria) this;
        }

        public Criteria andU_ape_patNotBetween(String value1, String value2) {
            addCriterion("U_APE_PAT not between", value1, value2, "u_ape_pat");
            return (Criteria) this;
        }

        public Criteria andU_ape_matIsNull() {
            addCriterion("U_APE_MAT is null");
            return (Criteria) this;
        }

        public Criteria andU_ape_matIsNotNull() {
            addCriterion("U_APE_MAT is not null");
            return (Criteria) this;
        }

        public Criteria andU_ape_matEqualTo(String value) {
            addCriterion("U_APE_MAT =", value, "u_ape_mat");
            return (Criteria) this;
        }

        public Criteria andU_ape_matNotEqualTo(String value) {
            addCriterion("U_APE_MAT <>", value, "u_ape_mat");
            return (Criteria) this;
        }

        public Criteria andU_ape_matGreaterThan(String value) {
            addCriterion("U_APE_MAT >", value, "u_ape_mat");
            return (Criteria) this;
        }

        public Criteria andU_ape_matGreaterThanOrEqualTo(String value) {
            addCriterion("U_APE_MAT >=", value, "u_ape_mat");
            return (Criteria) this;
        }

        public Criteria andU_ape_matLessThan(String value) {
            addCriterion("U_APE_MAT <", value, "u_ape_mat");
            return (Criteria) this;
        }

        public Criteria andU_ape_matLessThanOrEqualTo(String value) {
            addCriterion("U_APE_MAT <=", value, "u_ape_mat");
            return (Criteria) this;
        }

        public Criteria andU_ape_matLike(String value) {
            addCriterion("U_APE_MAT like", value, "u_ape_mat");
            return (Criteria) this;
        }

        public Criteria andU_ape_matNotLike(String value) {
            addCriterion("U_APE_MAT not like", value, "u_ape_mat");
            return (Criteria) this;
        }

        public Criteria andU_ape_matIn(List<String> values) {
            addCriterion("U_APE_MAT in", values, "u_ape_mat");
            return (Criteria) this;
        }

        public Criteria andU_ape_matNotIn(List<String> values) {
            addCriterion("U_APE_MAT not in", values, "u_ape_mat");
            return (Criteria) this;
        }

        public Criteria andU_ape_matBetween(String value1, String value2) {
            addCriterion("U_APE_MAT between", value1, value2, "u_ape_mat");
            return (Criteria) this;
        }

        public Criteria andU_ape_matNotBetween(String value1, String value2) {
            addCriterion("U_APE_MAT not between", value1, value2, "u_ape_mat");
            return (Criteria) this;
        }

        public Criteria andU_conIsNull() {
            addCriterion("U_CON is null");
            return (Criteria) this;
        }

        public Criteria andU_conIsNotNull() {
            addCriterion("U_CON is not null");
            return (Criteria) this;
        }

        public Criteria andU_conEqualTo(String value) {
            addCriterion("U_CON =", value, "u_con");
            return (Criteria) this;
        }

        public Criteria andU_conNotEqualTo(String value) {
            addCriterion("U_CON <>", value, "u_con");
            return (Criteria) this;
        }

        public Criteria andU_conGreaterThan(String value) {
            addCriterion("U_CON >", value, "u_con");
            return (Criteria) this;
        }

        public Criteria andU_conGreaterThanOrEqualTo(String value) {
            addCriterion("U_CON >=", value, "u_con");
            return (Criteria) this;
        }

        public Criteria andU_conLessThan(String value) {
            addCriterion("U_CON <", value, "u_con");
            return (Criteria) this;
        }

        public Criteria andU_conLessThanOrEqualTo(String value) {
            addCriterion("U_CON <=", value, "u_con");
            return (Criteria) this;
        }

        public Criteria andU_conLike(String value) {
            addCriterion("U_CON like", value, "u_con");
            return (Criteria) this;
        }

        public Criteria andU_conNotLike(String value) {
            addCriterion("U_CON not like", value, "u_con");
            return (Criteria) this;
        }

        public Criteria andU_conIn(List<String> values) {
            addCriterion("U_CON in", values, "u_con");
            return (Criteria) this;
        }

        public Criteria andU_conNotIn(List<String> values) {
            addCriterion("U_CON not in", values, "u_con");
            return (Criteria) this;
        }

        public Criteria andU_conBetween(String value1, String value2) {
            addCriterion("U_CON between", value1, value2, "u_con");
            return (Criteria) this;
        }

        public Criteria andU_conNotBetween(String value1, String value2) {
            addCriterion("U_CON not between", value1, value2, "u_con");
            return (Criteria) this;
        }

        public Criteria andU_estadoIsNull() {
            addCriterion("U_ESTADO is null");
            return (Criteria) this;
        }

        public Criteria andU_estadoIsNotNull() {
            addCriterion("U_ESTADO is not null");
            return (Criteria) this;
        }

        public Criteria andU_estadoEqualTo(String value) {
            addCriterion("U_ESTADO =", value, "u_estado");
            return (Criteria) this;
        }

        public Criteria andU_estadoNotEqualTo(String value) {
            addCriterion("U_ESTADO <>", value, "u_estado");
            return (Criteria) this;
        }

        public Criteria andU_estadoGreaterThan(String value) {
            addCriterion("U_ESTADO >", value, "u_estado");
            return (Criteria) this;
        }

        public Criteria andU_estadoGreaterThanOrEqualTo(String value) {
            addCriterion("U_ESTADO >=", value, "u_estado");
            return (Criteria) this;
        }

        public Criteria andU_estadoLessThan(String value) {
            addCriterion("U_ESTADO <", value, "u_estado");
            return (Criteria) this;
        }

        public Criteria andU_estadoLessThanOrEqualTo(String value) {
            addCriterion("U_ESTADO <=", value, "u_estado");
            return (Criteria) this;
        }

        public Criteria andU_estadoLike(String value) {
            addCriterion("U_ESTADO like", value, "u_estado");
            return (Criteria) this;
        }

        public Criteria andU_estadoNotLike(String value) {
            addCriterion("U_ESTADO not like", value, "u_estado");
            return (Criteria) this;
        }

        public Criteria andU_estadoIn(List<String> values) {
            addCriterion("U_ESTADO in", values, "u_estado");
            return (Criteria) this;
        }

        public Criteria andU_estadoNotIn(List<String> values) {
            addCriterion("U_ESTADO not in", values, "u_estado");
            return (Criteria) this;
        }

        public Criteria andU_estadoBetween(String value1, String value2) {
            addCriterion("U_ESTADO between", value1, value2, "u_estado");
            return (Criteria) this;
        }

        public Criteria andU_estadoNotBetween(String value1, String value2) {
            addCriterion("U_ESTADO not between", value1, value2, "u_estado");
            return (Criteria) this;
        }

        public Criteria andRol_idIsNull() {
            addCriterion("ROL_ID is null");
            return (Criteria) this;
        }

        public Criteria andRol_idIsNotNull() {
            addCriterion("ROL_ID is not null");
            return (Criteria) this;
        }

        public Criteria andRol_idEqualTo(Integer value) {
            addCriterion("ROL_ID =", value, "rol_id");
            return (Criteria) this;
        }

        public Criteria andRol_idNotEqualTo(Integer value) {
            addCriterion("ROL_ID <>", value, "rol_id");
            return (Criteria) this;
        }

        public Criteria andRol_idGreaterThan(Integer value) {
            addCriterion("ROL_ID >", value, "rol_id");
            return (Criteria) this;
        }

        public Criteria andRol_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("ROL_ID >=", value, "rol_id");
            return (Criteria) this;
        }

        public Criteria andRol_idLessThan(Integer value) {
            addCriterion("ROL_ID <", value, "rol_id");
            return (Criteria) this;
        }

        public Criteria andRol_idLessThanOrEqualTo(Integer value) {
            addCriterion("ROL_ID <=", value, "rol_id");
            return (Criteria) this;
        }

        public Criteria andRol_idIn(List<Integer> values) {
            addCriterion("ROL_ID in", values, "rol_id");
            return (Criteria) this;
        }

        public Criteria andRol_idNotIn(List<Integer> values) {
            addCriterion("ROL_ID not in", values, "rol_id");
            return (Criteria) this;
        }

        public Criteria andRol_idBetween(Integer value1, Integer value2) {
            addCriterion("ROL_ID between", value1, value2, "rol_id");
            return (Criteria) this;
        }

        public Criteria andRol_idNotBetween(Integer value1, Integer value2) {
            addCriterion("ROL_ID not between", value1, value2, "rol_id");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table usuario
     *
     * @mbggenerated do_not_delete_during_merge Sat Nov 22 18:09:08 COT 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table usuario
     *
     * @mbggenerated Sat Nov 22 18:09:08 COT 2014
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}